name: Java CI/CD

on:
  push:
    branches:
      - backend-y

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Decode and store the SSH private key
      - name: Set up SSH key
        run: |
          mkdir -p $env:USERPROFILE\.ssh
          ${{ secrets.SSH_PRIVATE_KEY }} | Out-File -Encoding ASCII -FilePath $env:USERPROFILE\.ssh\id_rsa

      - name: Print current directory
        run: |
          cat $env:USERPROFILE\.ssh\id_rsa

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Print current directory
        run: |
          pwd
          dir -Force

      # Deploy using SCP
      - name: Deploy to server
        run: scp -v -i "$env:USERPROFILE\.ssh\id_rsa" ./target/backend-0.0.1-SNAPSHOT.jar ubuntu@150.158.39.251:/home/ubuntu/phase2/


      # Restart the JAR file
      - name: Restart JAR file
        run: ssh -i $env:USERPROFILE\.ssh\id_rsa ubuntu@150.158.39.251 'pkill -f backend-0.0.1-SNAPSHOT.jar && nohup java -jar /home/ubuntu/phase2/backend-0.0.1-SNAPSHOT.jar &'
