name: Java CI/CD

on:
  push:
    branches:
      - backend-y

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'ubuntu'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2
        with:
          server: 150.158.39.251
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './target/backend-0.0.1-SNAPSHOT.jar'
          remote_path: '/home/ubuntu/phase2/'

      - name: Stop old JAR file and Start new JAR file
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@150.158.39.251 'pkill -f backend-0.0.1-SNAPSHOT.jar && nohup java -jar /home/ubuntu/phase2/backend-0.0.1-SNAPSHOT.jar &'
