name: Run Tests

on:
  push:
    branches:
      - backend-yyz

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: software_practice_phase1
        ports:
          - 3306:3306
        options: --health-cmd='mysqladmin ping --silent' --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'


      - name: Wait for MySQL to be ready
        run: |
          for i in `seq 1 60`; do
          if echo 'SELECT 1' | mysql --host=127.0.0.1 --port=3306 --user=root --password=123456 software_practice_phase1 &> /dev/null; then
           echo "MySQL is ready"
           break
          fi
          echo "Waiting for MySQL..."
          sleep 1
          done

      - name: Build and Test
        run: mvn clean test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/software_practice_phase1
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: 123456
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports

  save-reports:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download test reports artifact
        uses: actions/download-artifact@v2
        with:
          name: test-reports
          path: test-reports
